{% set name = "pyads" %}
{% set version = "3.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d69e5d4bf227adabc3d2e25877a3e2fbfc2644d7057719b3cc765115581ca15d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<36]

requirements:
  build:
    - make  # [linux]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyads  # [not win]

about:
  home: https://github.com/stlehmann/pyads
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python wrapper for TwinCAT ADS
  description: |
    This is a python wrapper for TwinCATs ADS library. It provides python functions for
    communicating with TwinCAT devices. pyads uses the C API provided by TcAdsDll.dll on
    Windows adslib.so on Linux. The documentation for the ADS API is available on
    infosys.beckhoff.com.
  doc_url: https://pyads.readthedocs.io
  dev_url: https://github.com/stlehmann/pyads

extra:
  recipe-maintainers:
    - marscher
    - stlehmann
