{% set name = "pyads" %}
{% set version = "3.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stlehmann/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94f0497ec1a522ae2a6d8484b7f81c9ee9adc3f8364091b19080b499c7053987

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyads  # [not win]

about:
  home: https://github.com/stlehmann/pyads
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python wrapper for TwinCAT ADS
  description: |
    This is a python wrapper for TwinCATs ADS library. It provides python functions for
    communicating with TwinCAT devices. pyads uses the C API provided by TcAdsDll.dll on
    Windows adslib.so on Linux. The documentation for the ADS API is available on
    infosys.beckhoff.com.
  doc_url: https://pyads.readthedocs.io
  dev_url: https://github.com/stlehmann/pyads

extra:
  recipe-maintainers:
    - stlehmann
