{% set name = "pyads" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 462a809fe96da5bcd27136479e380ef8901550d6620d45e8164d9d36d4e7594b

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py<36]

requirements:
  build:
    - make  # [linux]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    # we cannot import on Windows, because it tries to load the TinCAT dll directly.
    - pyads  # [not win]

about:
  home: https://github.com/stlehmann/pyads
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python wrapper for TwinCAT ADS
  description: |
    This is a python wrapper for TwinCATs ADS library. It provides python functions for
    communicating with TwinCAT devices. pyads uses the C API provided by TcAdsDll.dll on
    Windows adslib.so on Linux. The documentation for the ADS API is available on
    infosys.beckhoff.com.
  doc_url: https://pyads.readthedocs.io
  dev_url: https://github.com/stlehmann/pyads

extra:
  recipe-maintainers:
    - marscher
    - stlehmann
